language: rust
rust:
  - stable
  - beta
  - nightly
dist: bionic
install:
  - wget http://ffmpeg.org/releases/ffmpeg-4.3.1.tar.gz
  - tar xvf ffmpeg-4.3.1.tar.gz
  - cd ffmpeg-4.3.1 && ./configure --prefix=/usr --enable-shared --enable-gpl --enable-version3 --disable-programs --disable-doc && make && sudo make install
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
