language: rust
rust:
  - stable
  - beta
  - nightly
dist: bionic
addons:
  apt:
    packages:
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libswscale-dev
      - libswresample-dev
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
