[package]
name = "ac-ffmpeg"
version = "0.4.0"
authors = ["Ondrej Perutka <ondrej.perutka@angelcam.com>"]

[dependencies]
bytes       = "0.4"
lazy_static = "1.2"
libc        = "0.2"

[build-dependencies]
cc = "1.0"
